### ISSUE TITLE
rstudio: error when pushing to github

### ISSUE THREAD

**Issue by bbest** [OHI-Science/ohicore#104]
When pushing commits within RStudio to github, getting this error:

```
error: unable to read askpass response from 'rpostback-askpass'
fatal: could not read Username for 'https://github.com': Device not configured
```

![image](https://cloud.githubusercontent.com/assets/2837257/3069396/308befc8-e29b-11e3-9730-d2fe6609fc8d.png)

**Comment by drperpo** [comment]
Have same problem with ssh. My repo is also private so does not connect when I change to ssh. 
Any suggestions?

**Comment by paternogbc** [comment]
I have the same problem but when using my repo.wiki clone. There is no ssh option to clone.
Any idea?

**Comment by jules32** [comment]
Hi there, 

We've been able to solve the problem when we have encountered it and have written up the following instructions (we wrote this for our Ocean Health Index project, but the solution is obviously relevant far beyond our project). Instructions are in our [Ocean Health Index Manual](http://ohi-science.org/manual), in the [rpostback-askpass error section](http://ohi-science.org/manual/#rpostback-askpass-error).

```
error: unable to read askpass response from 'rpostback-askpass' * fatal: could not read Username for 'https://github.com': Device not configured 
```

**Comment by xrobin** [comment]
`git config --global credential.helper osxkeychain` fixed the problem here. Ssh was not available with the remote I was pushing to.
