### ISSUE TITLE
Fail to install ohi package 

### ISSUE THREAD

**Issue by anyalim** [OHI-Science/ohicore#183]
I successfully installed the devtools package but failed to install ohi package through using install_github('ohi-science/ohicore')

Error message is below
> install_github('ohi-science/ohicore')
Downloading GitHub repo ohi-science/ohicore@master
from URL https://api.github.com/repos/ohi-science/ohicore/zipball/master
Installing ohicore
"C:/PROGRA~1/R/R-33~1.1/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/ssss/AppData/Local/Temp/Rtmp0WpY3m/devtools26b03b0058a7/OHI-Science-ohicore-410cebb" --library="C:/Program Files/R/R-3.3.1/library" --install-tests 

* installing *source* package 'ohicore' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'DBI'
ERROR: lazy loading failed for package 'ohicore'
* removing 'C:/Program Files/R/R-3.3.1/library/ohicore'
Error: Command failed (1)

Could you help me to install the package?

Many thanks,
Anya

**Comment by bbest** [comment]
Hi Anya,

Please try again after installing the DBI package: install.packages('DBI').

I'm suggesting this based on this part of your error message:

there is no package called 'DBI' ERROR: lazy loading failed for package
'ohicore'

**Comment by anyalim** [comment]
Thanks for the suggestion.
Installing just "DBI" didn't solve the issue. However, based on your suggestion, I installed dozens of packages which were missing to install ohicore, ohicore is installed at last! Thank you very much!  

Now, I have another question. I got 18 warnings, which are 

1: replacing previous import ‘ggplot2::last_plot’ by ‘plotly::last_plot’ when loading ‘ohicore’
2: replacing previous import ‘git2r::config’ by ‘plotly::config’ when loading ‘ohicore’
3: replacing previous import ‘dplyr::summarise’ by ‘plyr::summarise’ when loading ‘ohicore’
4: replacing previous import ‘dplyr::rename’ by ‘plyr::rename’ when loading ‘ohicore’
5: replacing previous import ‘dplyr::arrange’ by ‘plyr::arrange’ when loading ‘ohicore’
6: replacing previous import ‘dplyr::failwith’ by ‘plyr::failwith’ when loading ‘ohicore’
7: replacing previous import ‘dplyr::count’ by ‘plyr::count’ when loading ‘ohicore’
8: replacing previous import ‘dplyr::desc’ by ‘plyr::desc’ when loading ‘ohicore’
9: replacing previous import ‘dplyr::summarize’ by ‘plyr::summarize’ when loading ‘ohicore’
10: replacing previous import ‘dplyr::mutate’ by ‘plyr::mutate’ when loading ‘ohicore’
11: replacing previous import ‘dplyr::id’ by ‘plyr::id’ when loading ‘ohicore’
12: replacing previous import ‘plyr::arrange’ by ‘dplyr::arrange’ when loading ‘ohicore’
13: replacing previous import ‘plyr::desc’ by ‘dplyr::desc’ when loading ‘ohicore’
14: replacing previous import ‘plyr::failwith’ by ‘dplyr::failwith’ when loading ‘ohicore’
15: replacing previous import ‘plyr::id’ by ‘dplyr::id’ when loading ‘ohicore’
16: replacing previous import ‘plyr::mutate’ by ‘dplyr::mutate’ when loading ‘ohicore’
17: replacing previous import ‘plyr::summarise’ by ‘dplyr::summarise’ when loading ‘ohicore’
18: replacing previous import ‘plyr::summarize’ by ‘dplyr::summarize’ when loading ‘ohicore’

Can I ignore them or should I do something?

**Comment by jules32** [comment]
Hi @anyalim, 

Glad you were able to install it. Those warning messages are fine to ignore (we will fix them in the future but they are fine for now).

**Comment by anyalim** [comment]
Thank you very much!!  Now I will explore ohicore more!
